### ISSUE TITLE
Pretrained checkpoint 

### ISSUE THREAD

**Issue by Gutianpei** [jaeyeonkim99/EnCLAP#2]
Thanks for the amazing work! Any estimate on releasing pretrained checkpoint? Excited to try it out!

**Comment by jaeyeonkim99** [comment]
Since the code was refactored from the original version for ICASSP submission, we are porting the weights of the pretrained checkpoints. We hope to release the pretrained checkpoints soon, probably during this week or the next week.

**Comment by MoayedHajiAli** [comment]
Hello @jaeyeonkim99. Do you any updates on the checkpoints? 
Thank you very much!.

**Comment by jaeyeonkim99** [comment]
Hello! We've just uploaded the link for the pretrained checkpoints. We apologize for the delayed release compared to what was expected. Please give it a try! Thank you.
