### ISSUE TITLE
Hello, what does the args'--ckpt' mean in the inference.py "python inference.py  --ckpt checkpoint_directory_with_config --clap_ckpt clap_ckpt_path --input input.wav"?

### ISSUE THREAD

**Issue by DthdZK** [jaeyeonkim99/EnCLAP#4]

**Comment by jaeyeonkim99** [comment]
Sorry for the late reply.

"--ckpt" refers to the checkpoint folder (e.g. "output/checkpoints/epoch_5") containing both the weight file (i.e., "pytorch_model.bin") and the config file (i.e., "config.json") of the model. Both files are automatically saved during training inside the output directory.

You can also refer to pretrained checkpoints as examples.

Thank you.
